/*
 * Copyright (c) 2026, WSO2 LLC. (https://www.wso2.com).
 *
 * WSO2 LLC. licenses this file to you under the Apache License,
 * Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

package main

import (
	"bytes"
	"flag"
	"fmt"
	"io"
	"os"
	"path/filepath"

	"github.com/wso2/api-platform/tests/framework/core/catalog"
	"github.com/wso2/api-platform/tests/framework/core/taxonomy"
	"github.com/wso2/api-platform/tests/framework/core/topology"
)

type options struct {
	mapPath  string
	features string
	suite    string
	output   string
	check    bool
}

func main() {
	if err := run(os.Args[1:], os.Stdout, os.Stderr); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func run(args []string, stdout, stderr io.Writer) error {
	fs := flag.NewFlagSet("taxonomy", flag.ContinueOnError)
	fs.SetOutput(stderr)
	opts := options{}
	fs.StringVar(&opts.mapPath, "map", "docs/capability-map.yml", "capability map path")
	fs.StringVar(&opts.features, "features", "suites/it/features", "feature directory")
	fs.StringVar(&opts.suite, "suite", "", "optional suite YAML for feature-to-runner validation")
	fs.StringVar(&opts.output, "output", "", "generated Markdown output path")
	fs.BoolVar(&opts.check, "check", false, "fail when output differs from generated content")
	if err := fs.Parse(args); err != nil {
		return err
	}
	if opts.check && opts.output == "" {
		return fmt.Errorf("-check requires -output")
	}

	capabilityMap, err := taxonomy.LoadMapFile(opts.mapPath)
	if err != nil {
		return err
	}
	paths, err := taxonomy.DiscoverFeatureFiles(opts.features)
	if err != nil {
		return err
	}
	var scenarios []taxonomy.Scenario
	for _, path := range paths {
		parsed, parseErr := taxonomy.ParseFeature(path)
		if parseErr != nil {
			return parseErr
		}
		scenarios = append(scenarios, parsed...)
	}
	if err := capabilityMap.ValidateScenarios(scenarios); err != nil {
		return err
	}
	if opts.suite != "" {
		if err := validateSuiteBindings(opts.suite, paths); err != nil {
			return err
		}
	}

	var generated bytes.Buffer
	if err := capabilityMap.RenderCoverageTree(&generated, scenarios); err != nil {
		return err
	}
	if opts.output == "" {
		_, err = stdout.Write(generated.Bytes())
		return err
	}
	if opts.check {
		existing, readErr := os.ReadFile(opts.output)
		if readErr != nil {
			return fmt.Errorf("taxonomy: read generated output %q: %w", opts.output, readErr)
		}
		if !bytes.Equal(existing, generated.Bytes()) {
			return fmt.Errorf("taxonomy: generated output %q is stale", opts.output)
		}
		return nil
	}
	if err := os.WriteFile(opts.output, generated.Bytes(), 0o644); err != nil {
		return fmt.Errorf("taxonomy: write generated output %q: %w", opts.output, err)
	}
	return nil
}

func validateSuiteBindings(suitePath string, discovered []string) error {
	registry, err := catalog.Registry()
	if err != nil {
		return fmt.Errorf("taxonomy: load catalog for suite binding validation: %w", err)
	}
	resolved, err := topology.LoadFile(suitePath, registry)
	if err != nil {
		return fmt.Errorf("taxonomy: load suite for binding validation: %w", err)
	}
	base := filepath.Dir(suitePath)
	bindings := make(map[string][]string)
	for _, block := range resolved.Blocks {
		for _, runner := range block.Runners {
			name := block.Name + "/" + runner.Name
			for _, feature := range runner.Features {
				path := feature
				if !filepath.IsAbs(path) {
					path = filepath.Join(base, path)
				}
				bindings[name] = append(bindings[name], filepath.Clean(path))
			}
		}
	}
	return taxonomy.ValidateBindings(discovered, bindings)
}
